language: python
dist: bionic
os: linux
python:
  - "3.6"

install:
  - pip install -U pip setuptools
  - pip install .
  - pip install pytest
  - pip freeze

script:
  - python -c "import tensorflow; import pyarrow"
  - python -c "import pyarrow; import tensorflow"
  - pytest tests

notifications:
  email: false
